### ISSUE TITLE
ENTREVISTA 3.0

### ISSUE THREAD

**Issue by SANDRAVELASCO** [SistemasTecTlaxiaco/actividad-2-entrevista-equipo-aras#2]
[ENTREVISTA-WEB3.0.pdf](https://github.com/user-attachments/files/16875713/ENTREVISTA-WEB3.0.pdf)

**Comment by Luz1727** [comment]
Preparacion 5%
Conocimiento ganado 5%
Informe : Falta introducción 4%
Redaccion: 5%
Calificación 19%

**Comment by josealfredo79** [comment]
No se ha evaluado este trabajo...

**Comment by josealfredo79** [comment]
Revisado..
